### ISSUE TITLE
the source code of Ping Viewer on github, but I can't find the code for return plot drawing?

### ISSUE THREAD

**Issue by leenpu** [bluerobotics/ping-viewer#1052]
![return plot](https://user-images.githubusercontent.com/61103934/204694919-93c2d8ed-7650-453f-b056-db14e6bf97d0.png)
Hello! I downloaded the source code of Ping Viewer on github, but I can't find the program for return plot drawing?

**Comment by patrickelectric** [comment]
It's the chart component:
https://github.com/bluerobotics/ping-viewer/blob/master/qml/Chart.qml

**Comment by leenpu** [comment]
> It's the chart component: https://github.com/bluerobotics/ping-viewer/blob/master/qml/Chart.qml

Okay, thank you！
