### ISSUE TITLE
Source code directly compiled error

### ISSUE THREAD

**Issue by leenpu** [bluerobotics/ping-viewer#1053]
![Source code compilation problem](https://user-images.githubusercontent.com/61103934/204703525-8f08184a-f555-4734-ba86-66cd3074aad7.png)
Hello! The source code I downloaded on github will make an error if I compile it directly with QT？

**Comment by patrickelectric** [comment]
Follow our build instructions here:
https://docs.bluerobotics.com/ping-viewer/build-instructions/

For windows, you need to build it in release mode or remove the kcrash dependency.

**Comment by patrickelectric** [comment]
Ok, did you found any problem with msvc2019 ?

**Comment by leenpu** [comment]
> 

yes, qt5.15.2 has an error while compiling, It shows that no cmake_cxx_compiler could be .......

**Comment by patrickelectric** [comment]
You should be able to use msvc2019.

Please provide the full error log of your compiler output.

**Comment by leenpu** [comment]
> You should be able to use msvc2019.
> 
> Please provide the full error log of your compiler output.

Unfortunately, an error occurred when compiling this source code！ the full error log of your compiler output:
![error](https://user-images.githubusercontent.com/61103934/205325113-11eaea06-ae2a-4a78-aa16-7195669f0570.png)
![problem](https://user-images.githubusercontent.com/61103934/205325263-683611e4-fb9a-46da-83a0-cf5b9ebc7583.png)

**Comment by patrickelectric** [comment]
You are compiling in debug mode, where KCrash is necessary, as said previously, please build in release mode for windows.

**Comment by leenpu** [comment]
> please build in release mode for windows

Thank you, build in release mode for windows， it compiled through except for three warnings！
![build informations](https://user-images.githubusercontent.com/61103934/205417746-3f92b593-f055-4715-8fbe-771236164da5.png)
![problems](https://user-images.githubusercontent.com/61103934/205417747-61717ab9-6b29-4f2f-b587-97ad85290415.png)

**Comment by patrickelectric** [comment]
I don't understand the text on the last two warning. The first one is new.
