### ISSUE TITLE
Ping1 firmware update options showing for a Ping2 device

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/ping-viewer#1079]
We should support Ping2 firmware update

**Comment by ES-Alexander** [comment]
As a couple of notes:

1. The distinguishing factor is expected to be `device_information.device_revision`, which is `1` for original Ping Sonar devices, and `2` for Ping2 Sonar devices
2. We need to make sure we're actually fetching this, since at the moment it's (usually?) showing up as `0`
    - The [`common.device_information`](https://docs.bluerobotics.com/ping-protocol/pingmessage-common/#4-device_information) request may be failing / timing out the first time, in which case it could be using the default `0` value
    - It's possible we're requesting the old [`ping1d.firmware_version`](https://docs.bluerobotics.com/ping-protocol/pingmessage-ping1d/#1200-firmware_version) message (either instead of `device_information`, or as a fallback), which [has `device_revision = 0` hardcoded in Ping Viewer](https://github.com/bluerobotics/ping-viewer/blob/578c7955808d05670b5ab658bb8564f26a383402/src/sensor/pingsensor.cpp#L126)
        - We can't meaningfully improve the handling of that message with current firmwares, because the message spec has `firmware_version.device_model` defined as `1` for all Ping1D devices, not just for the original Ping Sonar, so both firmwares report it as `1`
