### ISSUE TITLE
Add support for free-running mode

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#142]
Ping hardware has a command to enable continuous (non-polled) data stream. Try it out!

**Comment by patrickelectric** [comment]
from [here](https://github.com/bluerobotics/ping-protocol-cpp/blob/dev/src/protocol/templates/ping_protocol.json#L120).
```js
            "set_ping_rate_msec": {
                "id": "1004",
                "payload": [
                    {
                        "name": "rate_msec",
                        "type": "u16"
                    }
                ]
            },
```

**Comment by jaxxzer** [comment]
No, this one https://github.com/bluerobotics/ping-protocol-cpp/blob/dev/src/protocol/templates/ping_protocol.json#L542

**Comment by patrickelectric** [comment]
Our firmware does not have `continuous_start`
I'm receiving `GOT NACK "bad id"`
