### ISSUE TITLE
Add speed of sound config

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#143]

**Comment by patrickelectric** [comment]
That is something nice, should QGC calculate such values from the vehicle data ?

**Comment by jaxxzer** [comment]
Maybe something like that for advanced features in the future.

Right now, generally the user will have to know and tell the program what to use manually.

**Comment by jaxxzer** [comment]
https://github.com/bluerobotics/ping-protocol-cpp/blob/dev/src/protocol/templates/ping_protocol.json#L102
