### ISSUE TITLE
Weird issue when running generator from qmake

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#228]
I cannot find why this is happening
![screenshot 2018-07-24 12 24 20](https://user-images.githubusercontent.com/8315108/43152494-ad48e2ee-8f3c-11e8-915e-949178944a0e.png)

**Comment by patrickelectric** [comment]
I get the same thing here, it appears to be a bug in the qmake system, this line isn't a condition.

**Comment by patrickelectric** [comment]
This issue does not exist anymore
