### ISSUE TITLE
PingStatus: displaying binary data

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#231]
![screenshot 2018-07-26 22 34 41](https://user-images.githubusercontent.com/8315108/43298591-a14eb056-9124-11e8-8076-3adc4fa2eaef.png)

**Comment by patrickelectric** [comment]
@jaxxzer How can I replicate that ? Everything is working fine here.

**Comment by jaxxzer** [comment]
resolved in recent versions.
