### ISSUE TITLE
Do not erase config data during firmware upgrade

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#237]
There is data stored in mcu flash that needs to be retained.

**Comment by patrickelectric** [comment]
Are we erasing the eeprom ? Are we saving in the eeprom ?

**Comment by jaxxzer** [comment]
There is no eeprom (in any stm32 afaik). It is in flash memory with the program.

**Comment by patrickelectric** [comment]
Yes, you are correct. But, in this case we just need to write our variables in the highest memory address correct ?
In my mind, It'll not be possible to update the firmware or to add new variables without breaking the hardcoded address. Like binary compatibility between library versions.

**Comment by patrickelectric** [comment]
This is a "must-have" feature ? I don't see that as a high priority thing.

**Comment by jaxxzer** [comment]
It is must have, but not immediate priority.

I have dealt with this before. Generally, you dedicate the uppermost region for your non volatile storage, then tell the linker you have that much less flash. Then everything is fine as long as we don't do a mass erase.

**Comment by patrickelectric** [comment]
Moved to: https://github.com/bluerobotics/altimeter1-mirror/issues/4
