### ISSUE TITLE
Update main menu device connection settings at launch

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#253]
- connect via udp
- close application
- open application

application is reading over udp again, but main menu says serial and udp address is incorrect.

**Comment by jaxxzer** [comment]
` nc -ul 0.0.0.0 8888 > /dev/ttyUSB0 < /dev/ttyUSB0`

Should do it on another host to prevent serial device detection

**Comment by patrickelectric** [comment]
Just to update, this one works here, but the NC not.
```
socat -d -d -d -d -d UDP-LISTEN:1234,fork,reuseaddr,ignoreeof FILE:/dev/ttyUSB1,b115200,raw,ignoreeof
```
