### ISSUE TITLE
Gradual non-stop increase of cpu and memory usage

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#364]
On https://github.com/bluerobotics/ping-viewer/commit/7ea11cbd2b6f134d3907736731e8519f8a7e98c9
appimage,

- Only protocol detector log is enabled
- Open app, autoconnect udp via Companion
- Watch resources consumed more and more over the course of ~10 minutes
do {
- Enable protocol.ping log
- app hangs for ~30s
- app comes back, cpu (but not memory) resources drop
- disable protocol.ping log, resources spike back up again
} while(1)

**Comment by patrickelectric** [comment]
Result when all categories are **enabled**:
![2018-12-19_18-17](https://user-images.githubusercontent.com/1215497/50246387-1bbc1200-03cd-11e9-8a1e-f846d6c16b09.png)


Result when all categories are **disabled**:
![2018-12-19_18-30](https://user-images.githubusercontent.com/1215497/50246375-119a1380-03cd-11e9-8a41-54347f01b904.png)

This appears to be a problem in the log viewer rendering invisible widgets.
