### ISSUE TITLE
Restart program automatically after reset settings.

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#440]
The message we give out now says that we will do this, but it doesn't happen. Maybe we should change it in the meantime.

**Comment by patrickelectric** [comment]
Well, it's working here. Tested with stable AppImage and with compiled master branch.
Can you explain and give more details about how are you testing it ?

**Comment by patrickelectric** [comment]
![deepin-screen-recorder_pingviewer-x86_64 4 appimage_20190129103327](https://user-images.githubusercontent.com/1215497/51908630-459c2780-23c2-11e9-9561-7535bd226779.gif)

**Comment by patrickelectric** [comment]
@jaxxzer , can you confirm this ?

**Comment by jaxxzer** [comment]
Confirmed on Ubuntu xenial and archlinux.  Does not work from appimage or local build in any case.
