### ISSUE TITLE
Stable version is not a release!

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#443]
This is on v1.0.0. :man_facepalming:

![image](https://user-images.githubusercontent.com/8315108/51881801-72145d00-234a-11e9-899f-2bbf70450b94.png)

Related to #442 probably.

**Comment by patrickelectric** [comment]
![image](https://user-images.githubusercontent.com/1215497/51909725-34a0e580-23c5-11e9-9490-a92f01d57900.png)
Tested and working with last stable
