### ISSUE TITLE
Cannot edit scan start/stop

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#444]
There is some problem editing scan start/stop on v1.0.0, but the speed of sound works correctly.

**Comment by jaxxzer** [comment]
I've spent about an hour on this and have not fixed it.

|- -|- v3.24 -|- v3.26 -|
|---|---|---|
| t0.9.1 | working | working |
| v1.0.0 | not working | not working |

It appears related to the [focus](https://github.com/bluerobotics/ping-viewer/blob/master/qml/PingTextField.qml#L32-L44) of PingTextField. It's interesting that [speed of sound](https://github.com/bluerobotics/ping-viewer/blob/master/qml/MainMenu.qml#L67) works and[ scan range](https://github.com/bluerobotics/ping-viewer/blob/master/qml/MainMenu.qml#L177) does not.

Also #436 works without issue.

**Comment by patrickelectric** [comment]
![image](https://user-images.githubusercontent.com/1215497/51906808-ee478880-23bc-11e9-8e2c-60f393c127e7.png)
You can see in the gif of https://github.com/bluerobotics/ping-viewer/pull/437 that it was working before the rebase and commit correction.
Will try to see what is missing from the original work.
