### ISSUE TITLE
Ping starts to lag with manual length input 

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/ping-viewer#478]

**Comment by jaxxzer** [comment]
@brianhBR Can you post a minimal screen recording + corresponding gui + sensor log on dropbox and link it here?

**Comment by patrickelectric** [comment]
The logs are 8min long, going to update the .zip after new tests.
[problem.zip](https://github.com/bluerobotics/ping-viewer/files/2985677/problem.zip)

**Comment by patrickelectric** [comment]
can't replicate on latest release
