### ISSUE TITLE
Docs: Windows, Mac, and Linux Links go to wrong location

### ISSUE THREAD

**Issue by brianhBR** [bluerobotics/ping-viewer#483]
On https://docs.bluerobotics.com/ping-viewer/ page, the Windows, Mac, and Linux links under "Follow the setup instructions for your operating system:" take you to a different github.com page with link back to doc.  

Instead, Links should probably go to corresponding section of https://docs.bluerobotics.com/ping-viewer/

**Comment by patrickelectric** [comment]
Fixed by: https://github.com/bluerobotics/ping-viewer/commit/c5e06eb5562816c82b2d7e103ec1c49d9d2f68d2
