### ISSUE TITLE
Ping nack: `bad continuous request id: 6`

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#492]
Seen on ping-viewer master + firmware 3.26. May be a firmware bug...

**Comment by jaxxzer** [comment]
![image](https://user-images.githubusercontent.com/8315108/55598759-3e1e3500-5709-11e9-99ed-0e774e20cac7.png)

**Comment by patrickelectric** [comment]
general request requesting general request ?
lol

**Comment by patrickelectric** [comment]
We are not requesting id 6, or NACK message does not specify why the request failed. 
This is a list of requested messages before the NACK message appears:
```
>>> Requesting: 1215
>>> Requesting: 1205
>>> Requesting: 1300
>>> Requesting: 1200
>>> Requesting: 1201
>>> Requesting: 1203
>>> Requesting: 1215
>>> Requesting: 1205
>>> Requesting: 1206
>>> Requesting: 1214
>>> Requesting: 1213
>>> Requesting: 1202
>>> Requesting: 1205
>>> Requesting: 1214
>>> Requesting: 1213
>>> Requesting: 1202
>>> Requesting: 1205
```
I believe that is a firmware issue, what should we do related to it ?

**Comment by patrickelectric** [comment]
Yes, the sensor replies NACK for [ID 1300](https://github.com/bluerobotics/ping-protocol#1300-profile).

**Comment by jaxxzer** [comment]
Moved to ping-firmware repository: https://github.com/bluerobotics/ping-firmware/issues/2
