### ISSUE TITLE
Stop detecting after finding device, use the highest baud rate

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#567]
We should stop 'detecting' on a port after the device on the end of the line has been identified.

This includes trying multiple baudrates. We should just connect on the highest baudrate we can communicate.

**Comment by patrickelectric** [comment]
- The highest detection baud rate does not mean that is the best choice, we should identify the best baud rate running an baud rate measurement method and after that select the best for the current scenario.

- We also should aim to use a standard or at least a reduced number of baud rates to check (9600 and 115200) and after that negotiate or change the communication baud rate of the device, this will make it easier and fast to detect devices in the line.
