### ISSUE TITLE
Weird delay after leaving device manager

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#577]
After selecting a device from device manager there is a 5~10 second pause after the device manager window exits before any sensor activity or visualizer activity happens. This even affects the simulation links.

**Comment by patrickelectric** [comment]
I'm unable to replicate it in master branch, can you send a gif or a step-step to replicate it ?

**Comment by Williangalvani** [comment]
I see a much shorter pause here:
![pingpause](https://user-images.githubusercontent.com/4013804/62214436-7235f980-b37b-11e9-8f9c-a657ca2b3bcd.gif)

I can see it via USB or Ethernet. It seems to last ~1s here.

**Comment by patrickelectric** [comment]
Well, here is less than 1 to start to receive data from the sensor and to configure everything necessary before the sensor starts talking. I believe that such time is acceptable. I was not able to replicate the 5~10s delay.

**Comment by patrickelectric** [comment]
This is probably a issue related to the wait of the detection thread:
https://github.com/bluerobotics/ping-viewer/blob/f893d00f5cbd1380bf9f84a244bf3c3d9362aa28/src/devicemanager/devicemanager.cpp#L67

**Comment by jaxxzer** [comment]
This solved it for me :+1:
