### ISSUE TITLE
ping360: fix visualizer item alignment in sector view

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#579]
per https://github.com/bluerobotics/ping-viewer/pull/539#issuecomment-511931832

Things do not line up very well.
It would also be better if the visualizer also supported any arbitrary sector size.

![image](https://user-images.githubusercontent.com/8315108/61663961-ca943980-ac9f-11e9-821a-151c4cc0d07f.png)
![image](https://user-images.githubusercontent.com/8315108/61663969-cec05700-ac9f-11e9-8827-8ff64b285dfc.png)

**Comment by patrickelectric** [comment]
Fixed by: https://github.com/bluerobotics/ping-viewer/pull/613
