### ISSUE TITLE
Flip Vertically and Flip Horizontally should be changed to Top Up or Top Down

### ISSUE THREAD

**Issue by brianhBR** [bluerobotics/ping-viewer#583]
## Summary
Rather than having a setting to flip the plot vertically or horizontally we should have the user select the orientation of the sonar (i.e. Transducer head up or transducer head down). I'd recommend having a selectable, simple graphic with the sonar in each orientation for the user to select. 

 This will be more intuitive and might be applicable for both the ping1d and ping360

**Comment by patrickelectric** [comment]
Done, check #667
