### ISSUE TITLE
Improve PingStatus debug windows

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#603]
It's a bit annoying for the sensor debug window to be fixed in the center of the visualizer. I think we should move it to bottom-left and/or allow dragging. It will also be cool if we can spice the style with some cool monospace programmer font in lime green.

![Screenshot_20190726_113246](https://user-images.githubusercontent.com/8315108/61963216-19d8b380-af99-11e9-96e3-bb8be059eb5e.png)

**Comment by patrickelectric** [comment]
Fixed in #651
