### ISSUE TITLE
Menu Display on 4k

### ISSUE THREAD

**Issue by brianhBR** [bluerobotics/ping-viewer#624]
## Summary
Version: commit: 6ed95bc

Operating System: Linux (Ubuntu)

Control menu is not displayed properly, probably due to the 4k display. 

How to reproduce it: Open PingViewer > Click in the settings icon

## Additional information
![IMG_20190730_122018](https://user-images.githubusercontent.com/28631375/62158683-de095b00-b2c4-11e9-930b-c1c55f819b29.jpg)

**Comment by patrickelectric** [comment]
Thanks Kevin, indeed this is a problem that we got today after some rework in the submenu item. You can check the status here: https://github.com/bluerobotics/ping-viewer/issues/623
We also have a PR to fix that issue, I'll ping you after the next release with this fix.
https://github.com/bluerobotics/ping-viewer/pull/626

**Comment by patrickelectric** [comment]
@brianhBR 	you can check our last release, it'll not have the problem descried in this issue: https://github.com/bluerobotics/ping-viewer/releases/tag/continuous
