### ISSUE TITLE
S3 deployments

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#65]
Deploy to S3 so we can deploy multiple builds.

**Comment by patrickelectric** [comment]
Done by c007da819be3255c753ab46d8ba2633ad48ea00e
90f8446a0db1d654b08cf9dbda923c56a4990f19

**Comment by patrickelectric** [comment]
appveyor is not working, probably after the rename

**Comment by patrickelectric** [comment]
Travis also

**Comment by jaxxzer** [comment]
It looks like it is working: https://ci.appveyor.com/project/blueroboticsappveyor/ping-viewer/build/master-147-e17b40f/job/694920ect4oijb01#L3799

**Comment by jaxxzer** [comment]
And travis: https://travis-ci.org/bluerobotics/ping-viewer/jobs/397467346#L9253
