### ISSUE TITLE
round range display values to neat value

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#728]
It is not possible to achieve a range setting of exactly 2.00m at full resolution. The closest is 1.98m.

The range setting is 2m for ease of use. For clarity, we should display 2.00m on the chart.

The ping-viewer display is a visualization tool, not for making precision measurements. The 2 cm is not significant and can be safely ignored. Another option is to plot the data correctly, and pad the last 2cm of display with 'empty' data color.

Analysis can be performed on the log data with accurate numbers and math.

![Screenshot_20190826_140845](https://user-images.githubusercontent.com/8315108/63712144-0f654000-c80b-11e9-9777-711756d5ddf3.png)

https://github.com/bluerobotics/ping-viewer/issues/600 relevant

**Comment by patrickelectric** [comment]
Fix in #735
