### ISSUE TITLE
It is not possible to change from using the sonar to replaying a file.

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/ping-viewer#738]
Connect to the Ping360 and then click "Replay Data".
The screen darkens a little and stops responding to mouse inputs until I press "Esc".

**Comment by patrickelectric** [comment]
Not able to replicate it with last master branch.

**Comment by Williangalvani** [comment]
Just re-tested. The issue is still here, but apparently this only happens with udp links:
![deuruim](https://user-images.githubusercontent.com/4013804/64174208-2faa8580-ce2f-11e9-823f-edf77951458d.gif)

**Comment by patrickelectric** [comment]
@Williangalvani It's working without problems here, can you replicate this issue with the last master branch ?
