### ISSUE TITLE
Autobaud doesn't always result in the highest useable baudrate (2M)

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/ping-viewer#739]
I can get it to fail ~50% of the times I manually select a lower baudrate and click "autobaud"

**Comment by patrickelectric** [comment]
I was not able to replicate it with this error rate, here it fails only in less than 10% of the cases.

**Comment by patrickelectric** [comment]
@Williangalvani I'm still unable to replicate it, I'm getting 2M every single time in my tests since last month.
