### ISSUE TITLE
Antialiasing Slows Scan Rate on Mac

### ISSUE THREAD

**Issue by brianhBR** [bluerobotics/ping-viewer#741]
---
## Summary
Version: 2.0.2

Operating System:Mac (Mojave)

What is happening: The scan rate for ping360 is dramatically reduced from ~30 to ~20 FPS when antialiasing is on.

How to reproduce it: With a Ping360 attached open PingViewer > open display settings and toggle antialiasing.

**Comment by jaxxzer** [comment]
We should disable the setting by default or remove it altogether.

I think smooth data should probably be disabled by default also.

**Comment by jaxxzer** [comment]
I was not able to reproduce it on linux, scan rate was not impacted, and cpu load did not change significantly.

**Comment by patrickelectric** [comment]
@brianhBR just to make sure, I can see an improvement of 6~8Hz on mac when dissabling the anti-aliasing, is that what are you talking about ?
