### ISSUE TITLE
doc: formatting issues at https://docs.bluerobotics.com/ping-viewer/display-settings/#custom-gradients

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#742]

**Comment by patrickelectric** [comment]
What is the issue ? Is this fixed ?

**Comment by jaxxzer** [comment]
the text is huge ![image](https://user-images.githubusercontent.com/8315108/66076465-b2982c00-e512-11e9-9160-6e44b2866539.png)
