### ISSUE TITLE
ping1d performance suffers on t2

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#750]
t2.0.2 framerate is low and very jittery. The display does not update smoothly.

@50ping/s setting with no transducer plugged in, this is on a direct usb connection:
t2.0.2: 88% cpu
v1.1.1: 44% cpu

**Comment by jaxxzer** [comment]
Note this is still an issue with debug mode enabled.

**Comment by patrickelectric** [comment]
Debug mode is for debug. There is a commend in the code with a TODO note.

**Comment by jaxxzer** [comment]
On master today, I tried it without debug enabled, and the cpu is still quite high at 70% compared to 45% on v1.1.1.

Do you notice any difference @patrickelectric ?

**Comment by patrickelectric** [comment]
Both are using 27% of cpu here

**Comment by Williangalvani** [comment]
I noticed a large impact of enabling anti aliasing here.
