### ISSUE TITLE
The function of the baudrate in the firmware update section is unclear at first glance.

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/ping-viewer#766]
![Screenshot from 2019-09-23 11-29-12](https://user-images.githubusercontent.com/4013804/65434806-d0b8aa80-ddf5-11e9-905e-2d480f0a92b3.png)

It is not clear at first glance what this baud is for. This can confuse some users trying to change the sensor baudrate.

**Comment by patrickelectric** [comment]
This is for advanced users, probably you have the debug mode on.
