### ISSUE TITLE
ping1d: missing 'send reset' checkbox.

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#785]
We should put the 'send reset' checkbox back in the firmware update ui:

stable:
![Screenshot_20190930_234842](https://user-images.githubusercontent.com/8315108/65932781-00ab1380-e3dd-11e9-8199-b96aa9385466.png)

master:
![Screenshot_20190930_234451](https://user-images.githubusercontent.com/8315108/65932786-0274d700-e3dd-11e9-97ab-1889dfb72f0f.png)

**Comment by patrickelectric** [comment]
This is an advanced feature, it's only provided in "debug mode" in visualization settings.
