### ISSUE TITLE
Crash when shrinking window too small

### ISSUE THREAD

**Issue by NickNothom** [bluerobotics/ping-viewer#803]
## Summary
Version: 2.0.4

Operating System: Windows 10

What is happening: PingViewer crashes when the window is shrunk to the size of the depth reading in height or width. 

How to reproduce it: Open PingViewer with Ping1D, shrink the window in width or height until it is the size of the depth reading text label. 

## Additional information
https://streamable.com/3v34e

Log:
https://drive.google.com/open?id=1W0MiRy91xgu4U6akravUPvkFGUfYpX6M

**Comment by patrickelectric** [comment]
Hi @NickNothom can you test [this version](https://github.com/bluerobotics/ping-viewer/releases/download/continuous-fix_small_window/pingviewer_release.zip) ? It should fix your issue.

**Comment by NickNothom** [comment]
That version does not fix the issue for me

**Comment by jaxxzer** [comment]
:/

**Comment by NickNothom** [comment]
Let me know if I can provide any more helpful information

**Comment by jaxxzer** [comment]
Maybe this has something to do with the waveform plot on the right disappearing rather than the depth text (notice these two things happen coincidentally in @NickNothom's screenshot). @NickNothom can you make the depth text as small as possible by scroll wheeling over it, then try the same test.

**Comment by patrickelectric** [comment]
@NickNothom Please run the debug build in the continuous session and report the crash report.

**Comment by patrickelectric** [comment]
You can get the [debug build here](https://github.com/bluerobotics/ping-viewer/releases/download/continuous-fix_small_window/pingviewer_debug.zip)

**Comment by patrickelectric** [comment]
@NickNothom I just tested our last continuous version and its working fine unders windows:
![image](https://user-images.githubusercontent.com/1215497/66595802-0d183480-eb72-11e9-9617-9b0be60a7eff.png)

I was able to minimize to the 0x0 size.

**Comment by jaxxzer** [comment]
Works ok on linux.

**Comment by NickNothom** [comment]
0806d78 and 63f9308 are both still crashing for me on Windows 10. 

I can't run the debug build right now because:

`qrc:/main.qml:-1 File was compiled ahead of time with an incompatible version of Qt and the original file cannot be found. Please recompile`

It seems related to the depth text label to me, because if I move that label around it changes where the crash occurs. You'll see in the second example here that if I quickly make the windows smaller than the text label it's okay, but when I slowly resize it to be the same size as the text label, it crashes. 

https://streamable.com/y6hj3

**Comment by patrickelectric** [comment]
Hi Nick, yes the windows debug build is broken: https://github.com/bluerobotics/ping-viewer/issues/812
I'll try to test one more time here with the exactly steps that you did in your video next time that I boot under windows.

**Comment by patrickelectric** [comment]
Hi @NickNothom, I was able to replicate your issue in a new Windows installation and the last continuous build of appveyor.

**Comment by patrickelectric** [comment]
@NickNothom Can you test this build ?
https://ci.appveyor.com/api/buildjobs/i6wnkfwm4900cvfh/artifacts/pingviewer_release.zip

**Comment by NickNothom** [comment]
Fixed for me! 🎉
