### ISSUE TITLE
Change P360 ip Address

### ISSUE THREAD

**Issue by newJames** [bluerobotics/ping-viewer#842]
Hello！ I want to change the P360 sonar ip Address and port, but I have not found any way to change it,How can I change it ? Thank you

**Comment by jaxxzer** [comment]
Hello, the device functions as a dhcp client when it is first powered, and will be assigned an ip address if there is a dhcp server on the network. Changing the static ip address is not presently supported.  Can you let us know why you need to change the ip address?

**Comment by newJames** [comment]
I used to connect other sensors by static ip address and controled the ROV designed by mysrlf, and another question is that I tried to connect the p360 sonar by udp stream,but it does not work, I found that your website said Ethernet communications is not supported.

**Comment by newJames** [comment]
ok,I just make a dhcp server to connect the only p360 sonar sensor.

**Comment by patrickelectric** [comment]
@newJames will this fix your problem ?

**Comment by newJames** [comment]
Sure，Thankyou！
