### ISSUE TITLE
Firmware information is not received reliably

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#903]
![image](https://user-images.githubusercontent.com/8315108/75395575-b2813a00-58c0-11ea-96f0-ad6b9980657a.png)

**Comment by jaxxzer** [comment]
we should ask again if we don't get the answer.

**Comment by danielgud** [comment]
@bluerobotics/software-team The firmware options never populate on my work computer. Also had a customer that could not update firmware because of this which lead them to try the stm32flash procedure with a bad firmware file.

**Comment by patrickelectric** [comment]
Hi @danielgud can you share one of your GUI logs with that problem ?
I'm unable to replicate it here.

**Comment by patrickelectric** [comment]
Log from @danielgud 
[20200501-103708440.txt](https://github.com/bluerobotics/ping-viewer/files/4565794/20200501-103708440.txt)
