### ISSUE TITLE
Couldn't use NMEA simulator

### ISSUE THREAD

**Issue by 3nd0y** [bluerobotics/ping-viewer#924]
Hello,

I don't know if it's bug or request, but i think it's bug. Since i don't have echosounder so i use simulator with NMEA ouput $SDDBT and connected via COM port bridge emulator but ping viewer couldn't display it, 

the bridge port is COM1-COM2, COM1 connected to emulator, COM2 to ping viewer. I tried to monitor COM2 ouput using python serial, it gives output as expected but nor in ping viewer.. 

![image](https://user-images.githubusercontent.com/11195233/81868014-93837180-95ac-11ea-82c1-045e4644b206.png)

**Comment by patrickelectric** [comment]
Hi @3nd0y, Ping-Viewer only supports [ping-protocol](https://docs.bluerobotics.com/ping-protocol/) for now, but it's totally possible (and easy) to integrate NMEA input on it.
It's only necessary to create a device class for it, and everything else is should be really straightforward.

**Comment by patrickelectric** [comment]
Be free to open a PR.
