### ISSUE TITLE
ping360 latency issue

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#927]
tested on v2.1.0
The latency to next profile request on viewer side is very irregular, and sometimes way too large, here you can see it's almost 25ms
![image](https://user-images.githubusercontent.com/8315108/87727483-e547a400-c775-11ea-8842-843e3a076e0b.png)

here is the capture:
[ping360.zip](https://github.com/bluerobotics/ping-viewer/files/4934480/ping360.zip)

**Comment by patrickelectric** [comment]
Can you show a screnshot with both RX and TX, this 25ms can be the time of the sensor to do the sample.
Without the time between what ping-viewer receives (end of RX package) and what ping-viewer sends (start of TX package) the time in the screenshot does not help much. I would recommend to use the serial-TTL output and not the RS485-TTL.
There is also the RS485 switch time that may affect the translation between serial-TTL and RS485-TTL.

**Comment by patrickelectric** [comment]
The auto response messages should have fixed this issue since ping-viewer does not probe for messages anymore.
