### ISSUE TITLE
Vertical and Horizontal scaling/Mac dpi problems

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#93]
![image](https://user-images.githubusercontent.com/8315108/38891605-dee10688-4252-11e8-8c8c-4cccde0b5c3a.png)

**Comment by patrickelectric** [comment]
Probably it's necessary to use QPaintDevice::*Dpi* functions to calculate the correct resize of the frame.

**Comment by patrickelectric** [comment]
Fixed by #165
