### ISSUE TITLE
docs: add section on interpreting data

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-viewer#930]
Many beginners are confused about how an echosounder data should be read, and how the data on the screen relates to the beamwidth - etc.

**Comment by patrickelectric** [comment]
This:
https://bluerobotics.com/learn/understanding-and-using-scanning-sonars/
And this:
https://bluerobotics.com/learn/ping-sonar-technical-guide/

is not enough ?

**Comment by ES-Alexander** [comment]
Can this be closed now, given c40fb1f has been merged?

**Comment by patrickelectric** [comment]
Yep!
