### ISSUE TITLE
May I know how ping-viewer determine number of samples.

### ISSUE THREAD

**Issue by lixinghe1999** [bluerobotics/ping-viewer#946]
When we use Ping-viewer, we only need to set range, gain, and field of view.
However, we can't set the number of samples in the ping-viewer, which is required in API control and seems we can't adjust it based on range automatically like other parameters.
In my test, the number of samples/ data length can be 1200 or 666. They looks random and I am confused of how it works in ping-viewer. Are 1200 and 666 the default number of samples? Or ping-viewer has some rules to set it?
Thanks

**Comment by patrickelectric** [comment]
Hi @lixinghe1999,

That is [answered in our forum](https://discuss.bluerobotics.com/t/please-provide-some-answer-regards-ping360/6393/3), I would recommend to search there first to find your answering quicker.
