### ISSUE TITLE
Command line -c <connectionString> option type?

### ISSUE THREAD

**Issue by Kost38** [bluerobotics/ping-viewer#955]
Hello!
I can't use command line -c <connectionString> option because format of <connectionString> unknown. In general, i want to coonect to /tmp/COM1 port. Its weird placed by rov software and i can't move it. Also i can't symlink it to /dev/ttyUSB** because don't have a root.

**Comment by patrickelectric** [comment]
The command line string is for development, so we don't put enough time documenting it for now.
But it follows the format: TYPE:ARG1:ARG2
where it can be: serial:/dev/ttyACM0:115200 or udp:0.0.0.0:1234
